(function(_ds){var window=this;var kja=function(){let a;a='<div class="devsite-code-buttons-container" role="group" aria-label="'+_ds.$v("Action buttons");return(0,_ds.Q)(a+'"></div>')},lja=function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.W(a)+'" data-title="'+_ds.W(a)+'"></button>')},mja=function(a){a=
a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.W(a)+'" data-title="'+_ds.W(a)+'"></button>')},nja=function(a){const b=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+
_ds.W(a.pF)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.W(b)+'" data-title="'+_ds.W(b)+'"></button>')},oja=function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.W(a)+'" data-title="'+_ds.W(a)+'"></button>')};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(T){return T.replace(y,"&amp;").replace(B,"&lt;").replace(z,"&gt;")}function b(T,ca,wa){switch(T.nodeType){case 1:var xa=T.tagName.toLowerCase();ca.push("<",xa);var Fa=T.attributes,ab=Fa.length;if(ab){if(wa){for(var Za=[],Ha=ab;0<=--Ha;)Za[Ha]=Fa[Ha];Za.sort(function(Ia,jb){return Ia.name<jb.name?-1:Ia.name===jb.name?0:1});Fa=Za}for(Ha=0;Ha<ab;++Ha)Za=Fa[Ha],Za.specified&&ca.push(" ",Za.name.toLowerCase(),'="',Za.value.replace(y,"&amp;").replace(B,"&lt;").replace(z,"&gt;").replace(E,
"&quot;"),'"')}ca.push(">");for(Fa=T.firstChild;Fa;Fa=Fa.nextSibling)b(Fa,ca,wa);!T.firstChild&&/^(?:br|link|img)$/.test(xa)||ca.push("</",xa,">");break;case 3:case 4:ca.push(a(T.nodeValue))}}function c(T){function ca(la){if("\\"!==la.charAt(0))return la.charCodeAt(0);switch(la.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(la.substring(2),16)||la.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(la.substring(1),
8);default:return la.charCodeAt(1)}}function wa(la){if(32>la)return(16>la?"\\x0":"\\x")+la.toString(16);la=String.fromCharCode(la);if("\\"===la||"-"===la||"["===la||"]"===la)la="\\"+la;return la}function xa(la){var na=la.substring(1,la.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));la=[];for(var ja=[],Ma="^"===na[0],qa=Ma?1:0,Oa=na.length;qa<Oa;++qa){var ya=na[qa];switch(ya){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":la.push(ya);
continue}ya=ca(ya);if(qa+2<Oa&&"-"===na[qa+1]){var ob=ca(na[qa+2]);qa+=2}else ob=ya;ja.push([ya,ob]);65>ob||122<ya||(65>ob||90<ya||ja.push([Math.max(65,ya)|32,Math.min(ob,90)|32]),97>ob||122<ya||ja.push([Math.max(97,ya)&-33,Math.min(ob,122)&-33]))}ja.sort(function(Nc,je){return Nc[0]-je[0]||je[1]-Nc[1]});na=[];ya=[NaN,NaN];for(qa=0;qa<ja.length;++qa)Oa=ja[qa],Oa[0]<=ya[1]+1?ya[1]=Math.max(ya[1],Oa[1]):na.push(ya=Oa);ja=["["];Ma&&ja.push("^");ja.push.apply(ja,la);for(qa=0;qa<na.length;++qa)Oa=na[qa],
ja.push(wa(Oa[0])),Oa[1]>Oa[0]&&(Oa[1]+1>Oa[0]&&ja.push("-"),ja.push(wa(Oa[1])));ja.push("]");return ja.join("")}function Fa(la){for(var na=la.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),ja=na.length,Ma=[],qa=0,Oa=0;qa<ja;++qa){var ya=na[qa];"("===ya?++Oa:"\\"===ya.charAt(0)&&(ya=+ya.substring(1))&&ya<=Oa&&(Ma[ya]=-1)}for(qa=1;qa<Ma.length;++qa)-1===Ma[qa]&&(Ma[qa]=
++ab);for(Oa=qa=0;qa<ja;++qa)ya=na[qa],"("===ya?(++Oa,void 0===Ma[Oa]&&(na[qa]="(?:")):"\\"===ya.charAt(0)&&(ya=+ya.substring(1))&&ya<=Oa&&(na[qa]="\\"+Ma[Oa]);for(Oa=qa=0;qa<ja;++qa)"^"===na[qa]&&"^"!==na[qa+1]&&(na[qa]="");if(la.ignoreCase&&Za)for(qa=0;qa<ja;++qa)ya=na[qa],la=ya.charAt(0),2<=ya.length&&"["===la?na[qa]=xa(ya):"\\"!==la&&(na[qa]=ya.replace(/[a-zA-Z]/g,function(ob){ob=ob.charCodeAt(0);return"["+String.fromCharCode(ob&-33,ob|32)+"]"}));return na.join("")}for(var ab=0,Za=!1,Ha=!1,Ia=
0,jb=T.length;Ia<jb;++Ia){var ib=T[Ia];if(ib.ignoreCase)Ha=!0;else if(/[a-z]/i.test(ib.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Za=!0;Ha=!1;break}}var Ra=[];Ia=0;for(jb=T.length;Ia<jb;++Ia){ib=T[Ia];if(ib.global||ib.multiline)throw Error(""+ib);Ra.push("(?:"+Fa(ib)+")")}return new RegExp(Ra.join("|"),Ha?"gi":"g")}function d(T){var ca=0;return function(wa){for(var xa=null,Fa=0,ab=0,Za=wa.length;ab<Za;++ab)switch(wa.charAt(ab)){case "\t":xa||(xa=[]);xa.push(wa.substring(Fa,ab));
Fa=T-ca%T;for(ca+=Fa;0<=Fa;Fa-=16)xa.push("                ".substring(0,Fa));Fa=ab+1;break;case "\n":ca=0;break;default:++ca}if(!xa)return wa;xa.push(wa.substring(Fa));return xa.join("")}}function e(T,ca,wa,xa){ca&&(T={source:ca,Pw:T},wa(T),xa.push.apply(xa,T.jx))}function f(T,ca){var wa={},xa;(function(){for(var Za=T.concat(ca),Ha=[],Ia={},jb=0,ib=Za.length;jb<ib;++jb){var Ra=Za[jb],la=Ra[3];if(la)for(var na=la.length;0<=--na;)wa[la.charAt(na)]=Ra;Ra=Ra[1];la=""+Ra;Ia.hasOwnProperty(la)||(Ha.push(Ra),
Ia[la]=null)}Ha.push(/[\0-\uffff]/);xa=c(Ha)})();var Fa=ca.length,ab=function(Za){for(var Ha=Za.Pw,Ia=[Ha,"pln"],jb=0,ib=Za.source.match(xa)||[],Ra={},la=0,na=ib.length;la<na;++la){var ja=ib[la],Ma=Ra[ja],qa=void 0;if("string"===typeof Ma)var Oa=!1;else{var ya=wa[ja.charAt(0)];if(ya)qa=ja.match(ya[1]),Ma=ya[0];else{for(Oa=0;Oa<Fa;++Oa)if(ya=ca[Oa],qa=ja.match(ya[1])){Ma=ya[0];break}qa||(Ma="pln")}!(Oa=5<=Ma.length&&"lang-"===Ma.substring(0,5))||qa&&"string"===typeof qa[1]||(Oa=!1,Ma="src");Oa||(Ra[ja]=
Ma)}ya=jb;jb+=ja.length;if(Oa){Oa=qa[1];var ob=ja.indexOf(Oa),Nc=ob+Oa.length;qa[2]&&(Nc=ja.length-qa[2].length,ob=Nc-Oa.length);Ma=Ma.substring(5);e(Ha+ya,ja.substring(0,ob),ab,Ia);e(Ha+ya+ob,Oa,l(Ma,Oa),Ia);e(Ha+ya+Nc,ja.substring(Nc),ab,Ia)}else Ia.push(Ha+ya,Ma)}Za.jx=Ia};return ab}function g(T){var ca=[],wa=[];T.tripleQuotedStrings?ca.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):T.multiLineStrings?ca.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):ca.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);T.verbatimStrings&&wa.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var xa=T.hashComments;xa&&(T.cStyleComments?(1<xa?ca.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):ca.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),wa.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):ca.push(["com",/^#[^\r\n]*/,null,"#"]));T.cStyleComments&&(wa.push(["com",/^\/\/[^\r\n]*/,null]),wa.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));T.regexLiterals&&wa.push(["lang-regex",new RegExp("^"+q+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);T=T.keywords.replace(/^\s+|\s+$/g,"");T.length&&wa.push(["kwd",new RegExp("^(?:"+T.replace(/\s+/g,
"|")+")\\b"),null]);ca.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);wa.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(ca,wa)}function h(T){function ca(C){if(C>Ia){jb&&jb!==ib&&(Ha.push("</span>"),jb=null);!jb&&ib&&(jb=ib,Ha.push('<span class="',jb,'">'));var G=
a(na(wa.substring(Ia,C))).replace(ya?Ma:ja,"$1&#160;");ya=Oa.test(G);Ha.push(G.replace(qa,ph));Ia=C}}var wa=T.source,xa=T.XF,Fa=T.jx,ab=T.Yy,Za=T.Yz,Ha=[],Ia=0,jb=null,ib=null,Ra=0,la=0,na=d(window.PR_TAB_WIDTH),ja=/([\r\n ]) /g,Ma=/(^| ) /gm,qa=/\r\n?|\n/g,Oa=/[ \r\n]$/,ya=!0,ob=window._pr_isIE6();Za=ob?Za&&"PRE"===Za.tagName?6===ob?"&#160;\r\n":7===ob?"&#160;<br />\r":8===ob?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(ab){var Nc=[];for(ob=0;10>ob;++ob)Nc[ob]=Za+'</li><li class="L'+ob+'">';
var je="number"===typeof ab?ab-1:0;Ha.push('<ol class="linenums"><li class="L',je%10,'"');je&&Ha.push(' value="',je+1,'"');Ha.push(">");var ph=function(){var C=Nc[++je%10];return jb?"</span>"+C+'<span class="'+jb+'">':C}}else ph=Za;for(;;)if(Ra<xa.length&&(la<Fa.length?xa[Ra]<=Fa[la]:1))ca(xa[Ra]),jb&&(Ha.push("</span>"),jb=null),Ha.push(xa[Ra+1]),Ra+=2;else if(la<Fa.length)ca(Fa[la]),ib=Fa[la+1],la+=2;else break;ca(wa.length);jb&&Ha.push("</span>");ab&&Ha.push("</li></ol>");T.Yt=Ha.join("")}function k(T,
ca){for(var wa=ca.length;0<=--wa;){var xa=ca[wa];Y.hasOwnProperty(xa)?"console"in window&&console.warn("cannot override language handler %s",xa):Y[xa]=T}}function l(T,ca){T&&Y.hasOwnProperty(T)||(T=/^\s*</.test(ca)?"default-markup":"default-code");return Y[T]}function p(T){var ca=T.Xz,wa=T.Gy;T.Yt=ca;try{var xa=ca.match($a);ca=[];var Fa=0,ab=[];if(xa)for(var Za=0,Ha=xa.length;Za<Ha;++Za){var Ia=xa[Za];if(1<Ia.length&&"<"===Ia.charAt(0)){if(!mb.test(Ia))if(Gb.test(Ia))ca.push(Ia.substring(9,Ia.length-
3)),Fa+=Ia.length-12;else if(ma.test(Ia))ca.push("\n"),++Fa;else if(0<=Ia.indexOf("nocode")&&Ia.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var jb=Ia.match(Ka)[2],ib=1;var Ra=Za+1;a:for(;Ra<Ha;++Ra){var la=xa[Ra].match(Ka);if(la&&la[2]===jb)if("/"===la[1]){if(0===--ib)break a}else++ib}Ra<Ha?(ab.push(Fa,xa.slice(Za,Ra+1).join("")),Za=Ra):ab.push(Fa,Ia)}else ab.push(Fa,Ia)}else{ib=Ia;var na=ib.indexOf("&");if(0>na)var ja=ib;
else{for(--na;0<=(na=ib.indexOf("&#",na+1));){var Ma=ib.indexOf(";",na);if(0<=Ma){var qa=ib.substring(na+3,Ma),Oa=10;qa&&"x"===qa.charAt(0)&&(qa=qa.substring(1),Oa=16);var ya=parseInt(qa,Oa);isNaN(ya)||(ib=ib.substring(0,na)+String.fromCharCode(ya)+ib.substring(Ma+1))}}ja=ib.replace(F,"<").replace(N,">").replace(K,"'").replace(P,'"').replace(S," ").replace(Da,"&")}ca.push(ja);Fa+=ja.length}}var ob=ca.join("");T.source=ob;T.Pw=0;T.XF=ab;l(wa,ob)(T);h(T)}catch(Nc){"console"in window&&console.log(Nc&&
Nc.stack?Nc.stack:Nc)}}var q=function(){for(var T="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),ca="(?:^^|[+-]",wa=0;wa<T.length;++wa)ca+="|"+T[wa].replace(/([^=<>:&a-z])/g,"\\$1");return ca+")\\s*"}(),y=/&/g,B=/</g,z=/>/g,E=/"/g,F=/&lt;/g,N=/&gt;/g,K=/&apos;/g,P=/&quot;/g,Da=/&amp;/g,S=/&nbsp;/g,fa=/[\r\n]/g,cb=null,$a=
RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),mb=/^\x3c!--/,Gb=/^<!\[CDATA\[/,ma=/^<br\b/i,Ka=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,hb=g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Y={};k(hb,["default-code"]);k(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));k(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);k(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));k(g({keywords:"null true false"}),["json"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);k(g({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);k(g({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);k(g({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);k(g({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);k(g({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);k(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(T,ca,wa){T={Xz:T,Gy:ca,Yy:wa};p(T);return T.Yt};window.prettyPrint=function(T){function ca(){for(var ib=
window.PR_SHOULD_USE_CONTINUATION?Ha.now()+250:Infinity;Ia<xa.length&&Ha.now()<ib;Ia++){var Ra=xa[Ia];if(Ra.className&&0<=Ra.className.indexOf("prettyprint")){var la=Ra.className.match(/\blang-(\w+)\b/);la&&(la=la[1]);for(var na=!1,ja=Ra.parentNode;ja;ja=ja.parentNode)if(("pre"===ja.tagName||"code"===ja.tagName||"xmp"===ja.tagName)&&ja.className&&0<=ja.className.indexOf("prettyprint")){na=!0;break}if(!na){ja=Ra;null===cb&&(na=document.createElement("PRE"),na.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
cb=!/</.test(na.innerHTML));if(cb)if(na=ja.innerHTML,"XMP"===ja.tagName)na=a(na);else{if("PRE"!==ja.tagName&&fa.test(na)){var Ma="";ja.currentStyle?Ma=ja.currentStyle.whiteSpace:window.getComputedStyle&&(Ma=window.getComputedStyle(ja,null).whiteSpace);ja=!Ma||"pre"===Ma}else ja=!0;ja||(na=na.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{na=[];for(ja=ja.firstChild;ja;ja=ja.nextSibling)b(ja,na);na=na.join("")}na=na.replace(/(?:\r\n?|\n)$/,"");ja=Ra.className.match(/\blinenums\b(?::(\d+))?/);
jb={Xz:na,Gy:la,Yz:Ra,Yy:ja?ja[1]&&ja[1].length?+ja[1]:!0:!1};p(jb);if(Ra=jb.Yt)if(la=jb.Yz,"XMP"===la.tagName){na=document.createElement("PRE");for(ja=0;ja<la.attributes.length;++ja)Ma=la.attributes[ja],Ma.specified&&("class"===Ma.name.toLowerCase()?na.className=Ma.value:na.setAttribute(Ma.name,Ma.value));na.innerHTML=Ra;la.parentNode.replaceChild(na,la)}else la.innerHTML=Ra}}}Ia<xa.length?setTimeout(ca,250):T&&T()}for(var wa=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],xa=[],Fa=0;Fa<wa.length;++Fa)for(var ab=0,Za=wa[Fa].length;ab<Za;++ab)xa.push(wa[Fa][ab]);wa=null;var Ha=Date;Ha.now||(Ha={now:function(){return(new Date).getTime()}});var Ia=0,jb;ca()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:k,sourceDecorator:g,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[window.PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[window.PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[window.PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[window.PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[window.PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],
[window.PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],[window.PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[window.PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[window.PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[window.PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[window.PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);
window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[window.PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\v\f\r "],[window.PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[window.PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[window.PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[window.PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[window.PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[window.PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[window.PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],
[window.PR.PR_LITERAL,/^(?:true|false|null)\b/],[window.PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[window.PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[window.PR.PR_COMMENT,/^\/\/.*/],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[window.PR.PR_STRING,/'.'/],[window.PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[window.PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[window.PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[window.PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),
["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[window.PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[window.PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[window.PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[window.PR.PR_LITERAL,
/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_]\w*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[window.PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[window.PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[window.PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);window.PR.registerLangHandler(window.PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[window.PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[window.PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[window.PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[window.PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[window.PR.PR_KEYWORD,
/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],[window.PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[window.PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[window.PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[window.PR.PR_PLAIN,
/^[$a-zA-Z_][\w$]*/],[window.PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[window.PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[window.PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[window.PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_][\w-]*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[window.PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[window.PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[window.PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[window.PR.PR_LITERAL,/^(?:true|false|nil)\b/,
null],[window.PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[window.PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[window.PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[window.PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[window.PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[window.PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[window.PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[window.PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[window.PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[window.PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[window.PR.PR_PUNCTUATION,/^(?:\[|\])/]]),
["vb","vbs"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[window.PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[window.PR.PR_COMMENT,/^--[^\r\n]*/],[window.PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[window.PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[window.PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[window.PR.PR_LITERAL,
/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],[window.PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[window.PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[window.PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[window.PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[window.PR.PR_PLAIN,
/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[window.PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[window.PR.PR_TYPE,/^[&]\S+/,null,"&"],[window.PR.PR_TYPE,/^!\S*/,null,"!"],[window.PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[window.PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],
[window.PR.PR_PUNCTUATION,/^-/],[window.PR.PR_KEYWORD,/^\w+:[ \r\n]/],[window.PR.PR_PLAIN,/^\w+/]]),["yaml","yml"]);var pja=window;var rja=function(a){a.oa&&a.eventHandler.listen(a.oa,"click",()=>void a.setAttribute("dark-code",""));a.ra&&a.eventHandler.listen(a.ra,"click",()=>void a.removeAttribute("dark-code"));a.m&&a.eventHandler.listen(a.m,"click",()=>void qja(a));a.o&&a.eventHandler.listen(a.o,"click",()=>{const b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.cU(c,b):_ds.bU([a],b)})},qja=async function(a){var b=a.querySelector("pre:not(.devsite-copy-hide)");
if(b&&(b=[...b.childNodes],_ds.ts(document.body,b),a.ea)){const c=new _ds.am;let d;null==(d=a.m)||d.setAttribute("aria-label","Code sample copied to clipboard");_ds.$l(a.eventHandler,a.ea,"transitionend",()=>{c.h()});await c.promise;_ds.$l(a.eventHandler,a.ea,"transitionend",()=>{let e;null==(e=a.m)||e.setAttribute("aria-label",a.xa)})}},x4=class extends _ds.Vh{static get observedAttributes(){return["dark-code"]}constructor(){super(["devsite-snackbar"]);this.ea=this.ra=this.o=this.oa=this.m=this.h=
null;this.ya=!1;this.xa="";this.eventHandler=new _ds.x;this.Aa=new _ds.am;this.storage=new _ds.En;this.Ca=new _ds.JU(_ds.NU(_ds.MU()));_ds.Rh(this,(0,_ds.n)`no-toggle`)}whenReady(){return this.Aa.promise}async connectedCallback(){var a=await _ds.r();if(!this.ya){var b=this.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))this.setAttribute("no-copy",
""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");this.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");var c=b.getAttribute("data-label");this.xa=c?`${"Copy code sample"}: ${c}`:"Copy code sample";b.classList.contains("devsite-disable-code-toggle")&&(_ds.w(this,"no-toggle","",this),b.classList.remove("devsite-disable-code-toggle"))}if(b=this.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample"))this.setAttribute("js-fiddle",
""),b.classList.remove("devsite-enable-open-in-jsfiddle"),b.classList.add("devsite-jsfiddle-code-sample");if(this.hasAttribute("js-fiddle")&&b){c=["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"];for(var d of c)b.hasAttribute(`data-${d}`)&&(this.setAttribute(d,`${b.getAttribute(`data-${d}`)}`),b.removeAttribute(`data-${d}`))}this.prettyPrint();this.ya=!0}d=this.querySelector(".devsite-dark-code-default");b=null;this.storage.isAvailable()&&(b=this.storage.get("pref_dark-code"));if(d||b)this.setAttribute("dark-code",
""),d&&d.classList.remove("devsite-dark-code-default");this.Aa.h();try{await a.intersectionEnterForElement(this)}catch(g){if("IntersectionObserver not supported"!==g.message)return}if(a=this.querySelector(".devsite-code-buttons-container"))this.h=a;else{this.h=_ds.J(kja);if(this.hasAttribute("scope")){this.o=_ds.J(oja,{label:"Open code sample in JSFiddle"});(this.hasAttribute("jsfiddle-label")||this.hasAttribute("jsfiddle-title"))&&this.o.setAttribute("data-label",`${this.getAttribute("jsfiddle-label")||
this.getAttribute("jsfiddle-title")}`);var e;null==(e=this.h)||e.appendChild(this.o)}if(!this.hasAttribute("no-toggle")){this.oa=_ds.J(lja,{label:"Dark code theme"});var f;null==(f=this.h)||f.appendChild(this.oa);this.ra=_ds.J(mja,{label:"Light code theme"});let g;null==(g=this.h)||g.appendChild(this.ra)}if(!this.hasAttribute("no-copy")){e=this.getAttribute("data-copy-event-label");f="Click To Copy";e&&(f+=`: ${e}`);this.m=_ds.J(nja,{label:this.xa,pF:f});let g;null==(g=this.h)||g.appendChild(this.m)}this.prepend(this.h)}rja(this);
this.ea=document.querySelector("devsite-snackbar")}async disconnectedCallback(){(await _ds.r()).unregisterIntersectionForElement(this);this.h&&this.removeChild(this.h);_ds.A(this.eventHandler)}prettyPrint(){var a=[...this.getElementsByClassName("prettyprint")];for(const c of a){c.classList.remove("prettyprint");var b=(a=c.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?a[1]:void 0;let d;a=c.innerHTML;b=null!=(d=b)?d:"";a=a.replace(/(&#39;)/g,"'");a=pja.prettyPrintOne(a,b,void 0);_ds.ed(c,this.Ca.h(a));
c.getElementsByTagName("strong").length&&c.classList.add("devsite-code-highlight")}}async attributeChangedCallback(a,b,c){if("dark-code"===a&&b!==c&&!this.querySelector(".devsite-dark-code-default"))if(this.hasAttribute("dark-code")){this.storage.isAvailable()&&this.storage.set("pref_dark-code","1");await _ds.Jk();var d=[...document.querySelectorAll("devsite-code:not([dark-code])")].filter(f=>f!==this);for(var e of d)e.setAttribute("dark-code","")}else{this.storage.isAvailable()&&this.storage.remove("pref_dark-code");
await _ds.Jk();e=[...document.querySelectorAll("devsite-code[dark-code]")];for(d of e)d.removeAttribute("dark-code")}}};x4.prototype.attributeChangedCallback=x4.prototype.attributeChangedCallback;x4.prototype.disconnectedCallback=x4.prototype.disconnectedCallback;x4.prototype.connectedCallback=x4.prototype.connectedCallback;x4.prototype.whenReady=x4.prototype.whenReady;try{window.customElements.define("devsite-code",x4)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
