(function(_ds){var window=this;var Ifa=async function(){return _ds.t((await _ds.r()).getConfig(),17)},Kfa=async function(a){var b=Jfa;const c=await Ifa();if(c)return(await fetch(`${"https://dlp.googleapis.com/v2/projects/google.com:cloud-web-hats/content:deidentify"}?key=${c}`,{body:JSON.stringify({item:{value:a},deidentifyConfig:{infoTypeTransformations:{transformations:[{primitiveTransformation:{characterMaskConfig:{maskingCharacter:"*"}}}]}},inspectConfig:{minLikelihood:"POSSIBLE",infoTypes:b}}),headers:{"Content-Type":"application/json"},
method:"POST"})).json()};var Lfa=["https://inthecloud.withgoogle.com/startup/dl-cd.html"],Jfa=[{name:"FIRST_NAME"},{name:"LAST_NAME"},{name:"EMAIL_ADDRESS"},{name:"CREDIT_CARD_NUMBER"},{name:"DATE_OF_BIRTH"},{name:"DOMAIN_NAME"},{name:"PHONE_NUMBER"},{name:"URL"},{name:"US_SOCIAL_SECURITY_NUMBER"},{name:"IP_ADDRESS"}],Mfa={uS:"utm_source",bQ:"utm_medium",cL:"utm_campaign",tL:"utm_content",JS:"utm_term"},Nfa=function(a){a.eventHandler.listen(document.body,"devsite-analytics-observation",b=>{b=b.Ja.detail;"pageScroll"!==b.action&&
"pageScrollRaw"!==b.action||a.h.h({type:b.action,name:b.label||""})})},Ofa=function(a){a.eventHandler.listen(document.body,"devsite-analytics-sent-pageview",b=>{const c=b.Ja.detail;"trackPageview"===b.Ja.detail.event&&(b=DevsiteApp.hasMendelFlagAccess("Cloud","enable_cloudx_ping"),_ds.Cy(a.h,c,b))})},Pfa=function(a){a.eventHandler.listen(document,"cloud-track-search-focus",()=>{a.h.h({type:"search",name:"focus",metadata:{eventDetail:"n/a",search_suggest:"n/a",search_suggest_url:"n/a",position:"nav"}})});
a.eventHandler.listen(document,"cloud-track-search-input",()=>{a.h.h({type:"search",name:"input",metadata:{eventDetail:"n/a",search_suggest:"n/a",search_suggest_url:"n/a",position:"nav"}})});a.eventHandler.listen(document,"cloud-track-search-submit",async b=>{var c=b.Ja.detail.query,d=b.Ja.detail.lJ;let e="n/a",f="n/a";b="n/a";let g="submit";if(DevsiteApp.hasMendelFlagAccess("Cloud","enable_cloud_dlp_service")){const l=[];if(d){var h=d.closest(".devsite-result-item"),k="(unknown)";h instanceof HTMLElement&&
(h=h.id,h.includes("partial-query")?k="suggested search":h.includes("other-products")?k="product":h.includes("product")?k="page":h.includes("reference")&&(k="reference"),g+=` - ${k}`);d=d.closest(".devsite-result-item-link");d instanceof HTMLElement&&(h="",h=Array.from(d.children),h=h.length?h.map(p=>p instanceof HTMLElement?p.innerText:"").join(" "):d.innerText,"suggested search"===k?(k=j2(a,h).then(p=>f=p||"(dlp error)"),l.push(k)):(f=h,b=d.getAttribute("href")||"n/a"))}c&&(c=j2(a,c).then(p=>{e=
p||"(dlp error)";e=e.substring(0,100).replace(/([0-9]{5})([0-9]+)/g,"$1[c]")}),l.push(c));await Promise.all(l)}a.h.h({type:"search",name:g,metadata:{eventDetail:e,search_suggest:f,search_suggest_url:b,position:"nav"}})})},Qfa=function(a){a.eventHandler.listen(document.body,"cloudx-personalization-update",b=>{_ds.Ay(a.h,{Ea:b.Ja.detail.key,value:b.Ja.detail.value})})},k2=async function(){var a=Array.from(document.querySelectorAll(_ds.aK())).map(c=>window.customElements.whenDefined(c.localName));await Promise.all(a);
a=Rfa();var b=a.Jy;if(a.source&&b){b=Lfa.map(c=>`[href*="${c}"]`).join(",");b=document.querySelectorAll(b);for(const c of b)c instanceof HTMLAnchorElement&&Sfa(c,a)}},j2=async function(a,b){if(!b.length)return"";b=await Kfa(b).catch(c=>{a.h.h({type:"dlp error",name:JSON.stringify(c)})});return b?b.item.value:(a.h.h({type:"dlp error",name:"Unable to call DLP"}),null)},Rfa=function(){var a=(new URL(window.document.location.href)).searchParams;const b=a.get("utm_source"),c=a.get("utm_medium"),d=a.get("utm_campaign"),
e=a.get("utm_content");a=a.get("utm_term");return{source:b,Jy:c,XE:d,content:e,yJ:a}},Sfa=function(a,b){var c=a.getAttribute("href"),d=b.source,e=b.Jy,f=b.XE,g=b.content;b=b.yJ;if(c&&d&&e){c=new URL(c);d=[`${"utm_source"}=${d}`,`${"utm_medium"}=${e}`];f&&d.push(`${"utm_campaign"}=${f}`);g&&d.push(`${"utm_content"}=${g}`);b&&d.push(`${"utm_term"}=${b}`);f=Object.values(Mfa);for(const [h,k]of Array.from(c.searchParams))g=k,e=h.replace(";",""),f.includes(e)||(g?d.push(`${e}=${g}`):d.push(e));_ds.cd(a,
_ds.Zc(`${c.origin}${c.pathname}?${d.join("&")}`))}},Tfa=class extends _ds.Lu{constructor(){super(...arguments);this.h=new _ds.Dy;this.eventHandler=new _ds.x}connectedCallback(){super.connectedCallback();this.h.xp();_ds.zy(this.h);Nfa(this);Ofa(this);Pfa(this);Qfa(this);_ds.xy(this.h);k2();this.eventHandler.listen(document.body,"cloudtrack-decorate-urls",()=>{k2()})}disconnectedCallback(){super.disconnectedCallback();_ds.A(this.h.eventHandler);_ds.A(this.eventHandler)}};try{window.customElements.define("cloudx-track",Tfa)}catch(a){console.warn("CloudxTrack",a)};})(_ds_www);
